name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: timbru31/java-node
    
    steps:
      - name: Install dependencies
        run: |
          apt-get update -y
          apt-get install -y curl chromium-chromedriver 
          curl -O https://download.clojure.org/install/linux-install-1.10.2.774.sh
          chmod +x linux-install-1.10.2.774.sh && ./linux-install-1.10.2.774.sh
          npm install -g shadow-cljs
          npm install
          
      - uses: actions/checkout@v2      
        
      - name: Style Check
        run: |
          clojure -M:style check
          
      - name: Lint
        run:
          clojure -M:lint
      
      - name: Tests
        run:
         npm run tests
